project_id = "sjznikaxsivaoytefagi"

[functions.task-operations]
verify_jwt = false

[functions.send-approval-webhook]
verify_jwt = false

[functions.send-layout-webhook]
verify_jwt = false

[functions.manage-users]
verify_jwt = true

[functions.process-event-webhooks]
verify_jwt = false

[functions.check-offline-leads]
verify_jwt = false

[functions.export-database]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false
